### ISSUE TITLE
Simplification of game-list

### ISSUE THREAD

**Issue by DoganM95** [TBemme/galaxy-integration-psp#4]
Your readme says:

**This plugin uses a No-Intro Sony PlayStation Portable .dat file as an index to prepare a game id (using the serial) and title, in order to add it to your Library.**

Is there any specific reason for this?

Why not use each games ID, e.g. `UCUS-98618` for the game "`Daxter`" as a prefix instead of the overcomplicated database lookup from a `.dat` file?

In that case, a script could get the information of each `UMD_DATA.BIN` in `.iso`  files in the specified folder and create a list automatically and conveniently without any manual user interaction.

**Comment by DoganM95** [comment]
I just set up ps2 integration for gog, which worked perfectly fine and does not require any database:
https://github.com/AHCoder/galaxy-integration-ps2

it uses the "giant bomb api" : https://www.giantbomb.com/api/documentation/#toc-0-0
to get the according title/id for gog, could be an option for you to integrate into your code and simplify everything.

It also automatically gets the titles without using any game-list which lists the files. Could be worth taking a look into the ps2-plugins implementation.

Hope this was a bit of a useful information for you.

**Comment by TBemme** [comment]
Hi Dogen,

There was a few reasons I chose to use a No-Intro dat file. I was looking for source of information about as many PSP games as possible, that was consistent, and this was the best option I could find at the time.

I believe the Giant Bomb API requires each plugin user to set up their own third-party account/key, has limits (some other people putting this into their own plugins ran into this issue, where it would stop picking up games after a certain number.), and is dependent on another service being online, which is not ideal.

English-language games sites also often lack information about other language games, or may contain errors or inconsistencies in title romanisation. 

In my readme, I also mentioned "Games database related issues" - these are a critical problem, because they can only be fixed by GOG staff manually. At the time, it was taking several weeks for these issues to get resolved after reporting, since then... well. I have reported games database issues going back to September 2019 and it is now October 2020. It is looking possible they will never be fixed.

Consequently, a lot of the ways my integrations work were to try and preempt & avoid as many games database-related issues as possible. Looking at my own library of self-integrated games, I had an issue with about 10% of them.

-Trying to limit possible game submissions to a list of 'real', confirmed and physical games for the PSP platform, using a standard format for the title -- when a game_id is first submitted to the games database, it goes through some sort of automated matching that must be based on the title. If it fails, the game_id is marked as "spam" and becomes invisible from anyone's library. 

-The other issue is the first submitted title will become the 'default' title (while the display title can be changed in an individual user's library, it will still be the 'underlying' title for everyone). If there is a typo, it was accidentally applied to the wrong game etc these all have to be reported manually and wait for GOG's staff to fix.

As for UMD_DATA.BIN, it appears to only contains the serial/game_id. As described above, the title is where most of the difficulty lies (And - although there is a title field in PARAM.SFO, it is not consistent enough to use all the time.) I think your idea is to read this file for the serial, then match against the .dat, to lessen the involvement of the user? I did originally this plugin with idea of supporting any PSP games, even ones collected on your shelf, so I would not want to make it dependent on examining iso dumps, but that could be possible. The plugin would then need to include an iso parsing library, which might increase the size.

**Comment by DoganM95** [comment]
Ah, now i see the issues you ran into while creating the plugin and understand your design decisions much better.
Thank you very much for taking time to explain this!

Regarding the `UMD_DATA.BIN` and the `game_id`, my idea was to replace the No-Intro.dat file system completely by using the games ID's instead, e.g. `ULES01234`,  of which the region part could have been encoded in an `enum`, e.g. 
```
ULES -> 1
ULUS -> 2
...
UCES -> F
```
and use these encoded game_id's in some way as a replacement for No-Intro.dat,
but as you found No-Intro variant to be the most consistent, consider my suggestion obsolete.
